import math

# ── SensorFinger parameters (from SensorFinger/Config.py) ────────────────────
PoissonRatio   = 0.3
YoungsModulus  = 3000       # MPa — silicone-like

# Geometry (must match the mesh generated by generate_meshes.py)
Length         = 40.0       # mm, one bellows segment
NBellows       = 1
Height         = 20.0       # mm, finger cross-section height
Thickness      = 17.5       # mm, finger cross-section width
JointHeight    = 6.0
JointSlopeAngle = math.radians(30)

# Cable routing (Y = CableHeight in local finger frame, at the "back" surface)
CableHeight    = 17.75      # mm
# ─────────────────────────────────────────────────────────────────────────────

# ── Gripper layout ────────────────────────────────────────────────────────────
radius  = 30    # mm — default radial distance; overridden by add_gripper(finger_radius=...)
zHeight = 175   # mm — height of finger bases above table (+60 mm platform raise)
#   finger_sensor total length ≈ 135 mm (finger body 120 mm + fingernail 15 mm)
#   Finger tips will sit at z ≈ zHeigh135 = 5 mm (just above the table / food)
# ─────────────────────────────────────────────────────────────────────────────

cadFilePath = 'CAD/'


def _compute_finger_layout(numFingers: int, r: float):
    """
    Evenly-spaced finger positions on a circle of radius `r` in the XY plane.
    Returns (translations, angles):
      translations[i] = [tx, ty, zHeight]   (world-space finger base positions)
      angles[i]       = θ_i  (radians, measured from +Y axis, CCW)
    """
    angles = [i * 2 * math.pi / numFingers for i in range(numFingers)]
    translations = [[r * math.sin(a), r * math.cos(a), zHeight]
                    for a in angles]
    return translations, angles


def _rz_deg(p, angle_deg):
    """Apply Rz(angle_deg) to point p = [x, y, z]. Matches SOFA loader rotation."""
    r = math.radians(angle_deg)
    c, s = math.cos(r), math.sin(r)
    return [c * p[0] - s * p[1],
            s * p[0] + c * p[1],
            p[2]]


def add_gripper(rootNode, numGrippers: int = 5, finger_radius: float = radius):
    """
    Add a cable-driven SensorFinger gripper to the SOFA scene.

    Finger orientation
    ------------------
    Each SensorFinger is oriented so that:
      • Its length axis (local –Z) points straight DOWN  (world –Z).
      • Its cable surface (local +Y = CableHeight) faces OUTWARD (radially away
        from the gripper axis).  When the cable shortens the finger tip curls
        INWARD, closing the gripper.
    SOFA Euler rotation  [rx=0, ry=0, rz = –θ_deg]  achieves this by applying
    Rz(–θ) which leaves the –Z axis unchanged and rotates +Y to the outward
    radial direction at angle θ.

    Base fixation
    -------------
    A BoxROI selects the ≈20 vertices at the finger base (local z ≈ 0, world
    z ≈ zHeight).  RestShapeSpringsForceField holds them at their rest position.
    GripperController updates rest_position to translate the whole gripper.
    """
    translations, angles = _compute_finger_layout(numGrippers, finger_radius)
    gripper = rootNode.addChild('gripper')

    # Pre-compute cable routing geometry (same for every finger, in local frame)
    NSegments = 3
    CableHeightRelative = CableHeight - JointHeight
    LengthDiagonal  = CableHeightRelative / math.cos(JointSlopeAngle)
    JointStandoff   = LengthDiagonal * math.sin(JointSlopeAngle)

    cable_pts_local = []
    for seg in range(NSegments):
        cable_pts_local.append([0, CableHeight, -(Length * seg       + JointStandoff)])
        cable_pts_local.append([0, CableHeight, -(Length * (seg + 1) - JointStandoff)])
    pull_pt_local = [0, CableHeight, 0]   # fixed anchor at finger base

    for i in range(numGrippers):
        a  = angles[i]
        tx, ty, tz = translations[i]
        # Rz(180° – θ): keeps finger pointing down (–Z unchanged),
        # rotates cable surface (+Y) to face INWARD → tip curls inward when cable is pulled.
        rotation = [0, 0, 180 - a * 180 / math.pi]

        finger = gripper.addChild(f'finger{i+1}')

        # ── Solvers ──────────────────────────────────────────────────────────
        finger.addObject('EulerImplicitSolver', name='odesolver',
                         rayleighStiffness=0.1, rayleighMass=0.1)
        finger.addObject('SparseLDLSolver', name='preconditioner',
                         template='CompressedRowSparseMatrixd')

        # ── Volumetric FEM mesh ───────────────────────────────────────────────
        finger.addObject('MeshVTKLoader', name='loader',
                         filename=cadFilePath + 'finger_sensor.vtk',
                         rotation=rotation, translation=[tx, ty, tz])
        finger.addObject('MeshTopology', src='@loader', name='container')
        finger.addObject('MechanicalObject', name='tetras', template='Vec3d')
        finger.addObject('UniformMass', totalMass=0.0001)
        finger.addObject('TetrahedronFEMForceField', template='Vec3d', name='FEM',
                         method='large',
                         poissonRatio=PoissonRatio,
                         youngModulus=YoungsModulus)

        # ── Fix finger base ───────────────────────────────────────────────────
        # BoxROI selects vertices in a 60×60×10 world-space box around the base.
        # After init the selected indices are constant; GripperController updates
        # rest_position to move the gripper as a rigid body.
        bm  = 5      # half-height of the z-band (mm)
        bxy = 30     # half-width of the xy-box  (mm) — generous to cover any orientation
        box = [tx - bxy, ty - bxy, tz - bm,
               tx + bxy, ty + bxy, tz + bm]
        finger.addObject('BoxROI', name='boxROI', box=box, drawBoxes=False)
        finger.addObject('RestShapeSpringsForceField',
                         points='@boxROI.indices', stiffness=1e10)

        finger.addObject('LinearSolverConstraintCorrection', name='ccorrection')

        # ── Cable actuator ────────────────────────────────────────────────────
        # Transform cable points with the same rotation as the mesh loader:
        # Rz(180° – θ_deg), then translate to world position.
        rz = 180 - a * 180 / math.pi
        cable_pts_world = [[rp[0] + tx, rp[1] + ty, rp[2] + tz]
                           for rp in (_rz_deg(cp, rz) for cp in cable_pts_local)]
        pull_rp = _rz_deg(pull_pt_local, rz)
        pull_pt_world = [pull_rp[0] + tx, pull_rp[1] + ty, pull_rp[2] + tz]

        cables = finger.addChild('cables')
        cable1 = cables.addChild('cable1')
        cable1.addObject('MechanicalObject', position=cable_pts_world)
        cable1.addObject('CableConstraint', template='Vec3d', name='CableConstraint',
                         indices=list(range(2 * NSegments)),
                         pullPoint=pull_pt_world,
                         printLog=False,
                         value=0)          # 0 = no initial cable pull (gripper open)
        cable1.addObject('BarycentricMapping')

        # ── Collision model ───────────────────────────────────────────────────
        collisionFinger = finger.addChild('collisionFinger')
        collisionFinger.addObject('MeshSTLLoader', name='loader',
                                  filename=cadFilePath + 'finger_sensor.stl',
                                  rotation=rotation, translation=[tx, ty, tz])
        collisionFinger.addObject('MeshTopology', src='@loader', name='topo')
        collisionFinger.addObject('MechanicalObject', name='collisMech')
        collisionFinger.addObject('TriangleCollisionModel', selfCollision=False, group=1)
        collisionFinger.addObject('LineCollisionModel',     selfCollision=False, group=1)
        collisionFinger.addObject('PointCollisionModel',    selfCollision=False, group=1)
        collisionFinger.addObject('BarycentricMapping')

        # ── Visual model ──────────────────────────────────────────────────────
        # finger_sensor includes the finger body and fingernail as one mesh
        modelVisu = finger.addChild('visu')
        modelVisu.addObject('MeshSTLLoader', name='loader',
                            filename=cadFilePath + 'finger_sensor.stl',
                            rotation=rotation, translation=[tx, ty, tz])
        modelVisu.addObject('OglModel', src='@loader', color=[0.35, 0.60, 0.85, 0.85])
        modelVisu.addObject('BarycentricMapping')

    return gripper
